### ISSUE TITLE
FLUSH TABLES replication causing server hang

### ISSUE THREAD

**Issue by sjaakola** [mariadb-corporation/mysql-wsrep#237]
First found here: https://mariadb.atlassian.net/browse/MDEV-9224

**Comment by philip-galera** [comment]
Fixed in 5.6.28-25.13

**Comment by mstyne** [comment]
This issue still appears to be present; I encountered it after upgrading to Percona XtraDB Cluster 5.6.28-25.14 -- which per the release notes, should contain this fix. The cluster hung up on the `FLUSH TABLES` transaction as soon as our hourly backups kicked in.

Happy to provide any additional troubleshooting information to help track this down.

**Comment by ayurchen** [comment]
Michael, unfortunately we can't provide fixes for PXC. You'll need to first reproduce it against our binaries.
